name: job-matrix
on:
  push:

jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        node: [6, 8, 10]

        exclude:
          -
            os: ubuntu-18.04
            node: 6

        include:
          -
            os: macos-latest
            node: 10

    runs-on: ${{ matrix.os }}

    steps:
      -
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
